require "dissect/version"
require "dissect/client"
require "dissect/formatters/json"
require "dissect/models/finding"
require "dissect/finders/base"
require "dissect/finders/gem_finder"
require "octokit"
